факториал числа
js-tasks-ru/jsbasic-20220211_naumovn808 pull request #2
Opened 2022-02-10 17:49 UTC by naumovn808

2022-02-10 17:50 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2022-02-11 18:28 UTC, SinimaWath requested changes

2022-02-11 18:28 UTC, SinimaWath commented on 1-module/1-task/index.js
> +  var result = 1;
Давай не использовать var :) Устаревшая коснтрукция, здесь тебе подойдет `let`

2022-02-14 18:44 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-02-16 13:03 UTC, SinimaWath requested changes

2022-02-16 13:03 UTC, SinimaWath commented on 1-module/1-task/index.js
> +  var result = 1;
Надо править

2022-02-16 13:03 UTC, SinimaWath commented on 1-module/2-task/index.js
> +      alert("не должно быть пробелов");
Функция должна возвращать результат, через return: true/false, а не делать alert

2022-02-16 13:04 UTC, naumovn808 commented
То есть, мне необходимо исправить и заново создать пул реквест со всеми
направлениями?

ср, 16 февр. 2022 г., 18:03 Vladik Tarasov ***@***.***>:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In 1-module/2-task/index.js
> <https://github.com/js-tasks-ru/jsbasic-20220211_naumovn808/pull/2#discussion_r806942094>
> :
>
> > @@ -10,7 +10,17 @@ function print(text) {
>
>   * чтобы функция sayHello работала корректно
>
>   */
>
>  function isValid(name) {
>
> -  // ваш код...
>
> +  const a = " ";
>
> +  for (let i = 0; i < name.length; i++) {
>
> +    if (name[i] == a) {
>
> +      alert("не должно быть пробелов");
>
>
> Функция должна возвращать результат, через return: true/false, а не делать
> alert
> ------------------------------
>
> In 1-module/1-task/index.js
> <https://github.com/js-tasks-ru/jsbasic-20220211_naumovn808/pull/2#discussion_r806941557>
> :
>
> > @@ -1,3 +1,10 @@
>
>  function factorial(n) {
>
> -  // ваш код...
>
> +  var result = 1;
>
>
> Надо править
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/js-tasks-ru/jsbasic-20220211_naumovn808/pull/2#pullrequestreview-883140702>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AU2754ORNYADT3WVY46TFALU3OOBPANCNFSM5OBQIU6Q>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
> You are receiving this because you authored the thread.Message ID:
> ***@***.***
> com>
>

2022-02-17 09:35 UTC, SinimaWath commented
Нет, необходимо сделать коммит с исправлениями и запушить его

2022-02-20 08:53 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-02-20 10:50 UTC, SinimaWath requested changes

2022-02-20 10:50 UTC, SinimaWath commented on 1-module/2-task/index.js
> +  for (let i = 0; i < name.length; i++) {
Попробуй вызывать функцию `isValid(null)`

2022-03-01 17:18 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-03-06 10:21 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2022-03-06 12:19 UTC, SinimaWath approved these changes

2022-03-06 12:20 UTC, merged